### ISSUE TITLE
Rate limiting parameters

### ISSUE THREAD

**Issue by johnbumgarner** [nidhaloff/deep-translator#103]
I'm working to integrate the capabilities of this Python Package into my [open source project WordHoard](https://github.com/johnbumgarner/wordhoard).   I started writing code to use your Python package.  I noted that when I used the _Linguee Translator_ I get blocked within seconds.  I even get blocked if I add a 10 second delay between requests.  I cannot find any published guidelines on Linguee site for rate limiting.  I have contacted the vendor about this issue. 

Concerning the MyMemory Translator.  I also get blocked when using this translation service.  I have noted that MyMemory does have rate limits, which can be extended by adding an email parameter in the request. 

reference: https://mymemory.translated.net/doc/spec.php

Could you add this parameter to the MyMemory module?  If needed, I can do a Pull Request with the change. 

_Thanks in advance for reviewing this issue._

**Comment by johnbumgarner** [comment]
I'm closing this issue, because I developed a design my own solution, which I can maintain within my project.

**Comment by Beau-xu** [comment]
Hi @johnbumgarner ,
Have you figured out the limitation of Linguee translation?
