### ISSUE TITLE
[Feature Request] Support for libretranslate.com

### ISSUE THREAD

**Issue by fcolecumberri** [nidhaloff/deep-translator#106]
### Description

Support for https://libretranslate.com/

Also, I think in this case, the construct should have the url as parameter, since as described at https://github.com/LibreTranslate/LibreTranslate#mirrors , the project can be used locally or by other servers.

**Comment by ridicolos** [comment]
Hey @nidhaloff I am really new to contributing to open-source projects, but would love to help out here.

Could I take this issue? If all goes according to plan, I should be able to work on this in the next week. Hopefully it won't take me too much time to implement.

**Comment by nidhaloff** [comment]
@ridicolos Sure, just make a PR ;)

**Comment by nidhaloff** [comment]
@ridicolos Any progress on this feature?

**Comment by ridicolos** [comment]
@nidhaloff unfortunately not yet. If you want to take over the issue right away, you can. I'm not sure how soon I'll get to it. 

I'll probably manage to work on it a bit on sunday, but probably won't be able to finish it then.

**Comment by rahulbanerjee26** [comment]
Hi! Is this issue up for grabs?

**Comment by ridicolos** [comment]
Hey @rahulbanerjee26, because I unfortunately still haven't got around to starting the issue i don't think anything stands in the way and you can start with the implementation

**Comment by rahulbanerjee26** [comment]
Thanks, @ridicolos 

@nidhaloff could you please assign the issue to me? I should have a PR out in a week or so, thanks!

**Comment by nidhaloff** [comment]
Hi @rahulbanerjee26 thanks for joining. Normally I'm against assigning issues to specific people and I would prefer that anyone can work on it and just make a PR if something is ready. However, I would assign the issue to you in this case if you keep us updated about findings, changes, etc... ;)

**Comment by rahulbanerjee26** [comment]
Hi! @nidhaloff thank you!
Just to give you a bit of context, one of my courses in my university requires me to make an open-source contribution. I am a part of a team of 5 and the entire team will work together on making the PR.

We found an API Wrapper for [libretranslate](https://github.com/argosopentech/LibreTranslate-py) and are investigating it to see if it can be used. If the wrapper has any limitations, we plan on consuming the [API](https://github.com/LibreTranslate/LibreTranslate#mirrors) directly instead.

**Comment by nidhaloff** [comment]
@rahulbanerjee26 Sounds great. I'd rather not add a dependency/lib. The wrapper does not look mature and therefore, it would be great if you guys can make use of the existing dependencies. As you said, calling the API directly should be straightforward

**Comment by rahulbanerjee26** [comment]
Hi! @nidhaloff, we just made a PR for this feature.
