### ISSUE TITLE
Language detect

### ISSUE THREAD

**Issue by ObedH26** [nidhaloff/deep-translator#113]
Hello!
I am really interested to use your library and i still never done before.
Just a few question ;
It is very cool that i can detect which language a word come from, but is it possible to detect all the language it is from ? I mean many word have the same spelling in many different language could it be possible to know the list instead of one only as generally? Would be an awesome ad on if it isn't for now:)
Also i am a newbies to this so i dont get why i need an api_key to find the origine of a word and i am curious could you light me please ? 

So many translators available in your library it seem very cool thanks for it 🙏

**Comment by nidhaloff** [comment]
Hi @ObedH26, what do you mean by detecting all the languages a word is from? please provide what you did and paste your code so that we can know how to help you.

**Comment by ObedH26** [comment]
Good evening,
I do mean that for example;
"Difference" is spell in maltese and italian the same way: "differenza"
Also for example the word "book" is spell same in galician, italian, spanish and esperanto : "libro"
But the detection will always return me one language it would be pretty cool if it is able to return me all the langage from the translation is the same, but i guess it is more difficult, as it shall be more a dictionary than a translator to return me that but i let you see i dont really know :)

Also about the error i had, i am sorry about that i didn't realized it, i got an email nearly same moment i sended to you an issues which said me i was nearly the daily limit of detection so i guess this was the problem,didn't think i was that nearly i would have say way less.

And i would have one more question for you please.
- [ ] I am using GoogleTranslator for now ,i am getting issues to get an free api-key from Microsoft ill send them a mail. but i seen that often GoogleTranslator say me that a word have been detected from an language and its translate it to my language,but as on the official website from google, it is often an incorrect word that may look like or not either a word in the language it is detected from, but the fact google think it have a translate even if it dont exist as a word is a real problem to me. So i dont really know  microsoft translator , but do you know or think if this is safer,like the traduction is more true ?
I think people can suggest a translation to a word on google translate and maybe the AI of the website do it alone, i couldn't count how much time on the real google translate app it say me a piece of imaginary thing.And i really hope microsoft do better, from my language professor google is the worst thing but i would know if you know something about that?
Thanks

**Comment by ObedH26** [comment]
Sorry about the previous question i forgot i did open that, also i dont think i still have the file which came about.
And well about this one as i said i am not sure if there was a problem iwill write it here if that happen again but it was probably because i did my daily quota. I let you check the rest of my previous message also for you get what i firstly mean with my question

**Comment by nidhaloff** [comment]
@ObedH26 Ok I understand the issue now. However, it is really hard to detect many languages for a word. Even the google translator website can't do that. It would only suggest one language and you should manually choose another language if the AI didn't select what you want. Since deep-translator is built on top of these translators, it is impossible to detect a list or a dictionary of languages, therefore, it would only deliver the best result or rather the best "guess" of the language
