### ISSUE TITLE
Problem with library importation since the last update

### ISSUE THREAD

**Issue by ObedH26** [nidhaloff/deep-translator#116]
Hello.
I just upgraded your package, but it seem there is something wrong , ![image](https://user-images.githubusercontent.com/80646073/147695781-2f2024bf-ba5f-4e7f-9c54-6602ae55cdff.png)
It seem i am getting this error only when i use "from deep_translator import *", if i import manually the item needed it seem to work correctly.
Thanks, have a good evening

**Comment by nidhaloff** [comment]
Thanks for opening the issue! I will check it out asap

**Comment by nidhaloff** [comment]
@ObedH26 should be fixed in v1.7.0
