### ISSUE TITLE
Relax version constraints

### ISSUE THREAD

**Issue by Zethson** [nidhaloff/deep-translator#118]
* deep_translator version: latest
* Python version: 3.8
* Operating System: Arch

### Description

deep-translator cannot be added to a project of mine as a dependency because it requires click 8.x which conflicts with other dependencies of mine.
Could you in general please relax the version constraints a little bit?

Thanks

**Comment by nidhaloff** [comment]
@Zethson thanks for opening the issue! I already wanted to switch from click to argparse anyway. I think click is an unnecessary dependency in this case. According to the feedback I'm getting, not many people are using the cli feature

**Comment by nidhaloff** [comment]
@Zethson Fixed in v1.7.0
