### ISSUE TITLE
Error "ModuleNotFoundError: No Module named deep_translator", code does not execute

### ISSUE THREAD

**Issue by RodrigoSeger** [nidhaloff/deep-translator#119]
* deep_translator version: 1.6.1
* Python version: 3.10.1
* Operating System: Windows 10

### Description
I was trying to perform the test translation as it appears in the first example that is in the documentation and when I run the code, it appears like this: 
"from deep_translator import (GoogleTranslator,
ModuleNotFoundError: No module named 'deep_translator'"
I don't know if I installed something wrong, but in principle it should work.

### What I Did
![image](https://user-images.githubusercontent.com/42284961/149605797-8170c7c5-82b2-4c85-bcb6-5fb724908ad2.png)
![image](https://user-images.githubusercontent.com/42284961/149606055-69ff263b-c21d-4749-a234-dc3734e5f18c.png)
When I try to run "python -m pip install deep-translator", it gives me this:
![image](https://user-images.githubusercontent.com/42284961/149605927-a97c0d3b-d34d-4c74-ad9c-a55aa8ad54be.png)

**Comment by topguns837** [comment]
Hey @RodrigoSeger , It seems to be working fine on my system :)

deep_translator  : 1.6.1
Python version : 3.9.7
OS : Windows 10
pip version : 21.3.1

Installation step  : pip install -U deep-translator


![image](https://user-images.githubusercontent.com/51917087/152495086-e0e679df-8138-4e36-8ac7-4af5a28a544d.png)

**Comment by nidhaloff** [comment]
@RodrigoSeger Hi, apparently you didn't install the package correclty or maybe you are in a different python virtual environment. The best practice is to create a python3 virtual env and run pip install deep-translator there. This way you can make sure that the package has been installed correctly.
