### ISSUE TITLE
Usage from terminal documentation is outdated

### ISSUE THREAD

**Issue by brospars** [nidhaloff/deep-translator#120]
* deep_translator version: 1.6.1
* Python version: 3.7.4
* Operating System: Ubuntu 20.04

### Description

The usage from terminal documentation is outdated : https://deep-translator.readthedocs.io/en/latest/usage.html#usage-from-terminal

- The command is `deep_translator` and should be `deep-translator`
- The `--translator` option `Error: No such option: --translator` and should be `deep-translator translate`

### What I Did

```
deep_translator --translator "google" --source "english" --target "german" --text "happy coding"
```

**The correct command :**

```
deep-translator translate "google" --source "english" --target "german" --text "happy coding"
```

**Comment by nidhaloff** [comment]
@brospars thanks for noticing this. I tried to update the docs for the new v1.7.0 release. It should be up to date now
