### ISSUE TITLE
error while translating docx file

### ISSUE THREAD

**Issue by tcazw** [nidhaloff/deep-translator#121]
When I try to translate an docx file, the folowing error occur:

'utf-8' codec can't decode byte 0xc6 in position 15: invalid continuation byte

I believe it comes from how it read the docx files

**Comment by topguns837** [comment]
Can you post a code snippet as well ? (Also include the text file you want to translate)

**Comment by nidhaloff** [comment]
@tcazw Hi, can you post an example of your docx file and a code snippet?

**Comment by nidhaloff** [comment]
I'm closing the issue since I received no response but this should be already fixed anyway in new versions >= 1.8
