### ISSUE TITLE
Use lingua for language detection?

### ISSUE THREAD

**Issue by juligreen** [nidhaloff/deep-translator#122]
Just as a suggestion, this package was recently published: https://github.com/pemistahl/lingua-py
Since it's language detection capabilities seem to be very good it could replace the existing, api-based language detection.

**Comment by nidhaloff** [comment]
@juligreen thanks for the suggestion. However, I'm trying to keep the package simple, so I would rather not add dependencies for now. If the community required this feature then maybe we can do this ;) but now I think it's not necessary
