### ISSUE TITLE
[Question] Can this library be used to extract google readings?

### ISSUE THREAD

**Issue by MinmoTech** [nidhaloff/deep-translator#123]
Is it possible to extract readings from google translate (marked in image) with deep-translator?
Since it's often better at generating readings from japanese than offline libraries this is something I'd like to do.
![image](https://user-images.githubusercontent.com/25890405/150536487-1bb03c66-f37f-49e5-90a6-62ea58f6ba59.png)

Thank you for any help!

**Comment by nidhaloff** [comment]
@juligreen Hi, thanks for opening the issue. Yes, this is definitely possible since deep-translator is basically scraping the site.

It is not yet implemented though. I will check it out asap. 

Feel free to check this out if you want to contribute to the project

**Comment by lahdjirayhan** [comment]
I have explored and found that:

The mobile (?) version site used by this package `translate.google.com/m` -- notice the `m` there -- does not give out Latin transliteration/reading.

**The usual website**

![image](https://user-images.githubusercontent.com/52926983/179691503-8c4f289a-c991-45c8-acaa-ea002f5a8ae0.png)

**The mobile/lite website**

![image](https://user-images.githubusercontent.com/52926983/179691698-bd16ef3c-cc9f-4868-8184-8ed8b659d548.png)

Thought that this information could be informational and constructive to this issue thread.

**Comment by nidhaloff** [comment]
@lahdjirayhan Thanks for exploring this! According to your finding, this cannot be done in the current implementation. So I will close the issue
