### ISSUE TITLE
translate documentation to other languages

### ISSUE THREAD

**Issue by nidhaloff** [nidhaloff/deep-translator#13]
### Description

This is a great starting point for new comers that wish to contribute to the project. Translating the docs to other languages would be a great help.

**Comment by senk8** [comment]
Hello. I can translate documentation to Japanese.Can I work on this issue?

**Comment by nidhaloff** [comment]
@senk8 Thanks for joining the project. Of course you are very welcome to work on this ;)

**Comment by nidhaloff** [comment]
@senk8 Are you working further on providing the ja translation in the docs?

**Comment by senk8** [comment]
No,I'm not. Have this problem solve?
https://github.com/nidhaloff/deep_translator/pull/17#issuecomment-675641766
