### ISSUE TITLE
Issue while translating via Microsoft provider.

### ISSUE THREAD

**Issue by Unforevable** [nidhaloff/deep-translator#133]
* deep_translator version: 1.7.0
* Python version: 3.9.7
* Operating System: Win10

### Description

Hello. I was trying to translate from Zh-Hans source language via Microsoft localization provider.

### What I Did

```
Used Zh-Hans as source language.

Error:
zh-hans --> There is no support for the chosen language
```

It seems to be an error in constants.py:
```
MICROSOFT_CODES_TO_LANGUAGES = {translation_dict[k]['name'].lower(): k for k in translation_dict.keys()}
```
because prior in microsoft.py language register in request is lowered in MicrosoftTranslator class init method:

self.source = source.lower()

and further language to be supported by Microsoft is checked below: 

"is_language_supported" method:
```
if lang not in self._languages.keys():
    if lang not in self._languages.values():
       if lang not in self._languages.values():
         raise LanguageNotSupportedException(lang)
```
So if only keys lowered and not values also, the bug is reproduced.

Solving the issue:
Values should also be lowered.

```
MICROSOFT_CODES_TO_LANGUAGES = {translation_dict[k]['name'].lower(): k.lower() for k in translation_dict.keys()}
_languages = MICROSOFT_CODES_TO_LANGUAGES 
```

I do not know should I contribute this change (if it is correct) or just report, I'm new here)

**Comment by nidhaloff** [comment]
Hi @Unforevable, sure you can contribute and make this change https://github.com/nidhaloff/deep-translator/blob/master/deep_translator/microsoft.py

**Comment by nidhaloff** [comment]
@Unforevable I will check this out since I didn't receive a response from you
