### ISSUE TITLE
FREE??

### ISSUE THREAD

**Issue by ireneb612** [nidhaloff/deep-translator#135]
Is this tool always free or is it constrained to the free apis ??? 
Because it seems like it uses Google etc apis so maybe it's not free forever or anyway it is limited.

**Comment by nidhaloff** [comment]
Hi @ireneb612, Yes this tool is free as stated in the docs and description. It does not use the Google API! it uses web scraping when possible, therefore decoupling the need to use an API. On the other hand, some translators like DeepL require an API therefore, this tool gives the freedom to the user to use that API (if they want).

----

**You could ve formatted your question better**
