### ISSUE TITLE
libre no longer translating

### ISSUE THREAD

**Issue by Zethson** [nidhaloff/deep-translator#140]
* deep_translator version: 1.8.0
* Python version: 3.8
* Operating System: Linux

### Description

Translating "Ich mag Züge" which is German for "I like trains" with the libre flavor. 

The result is still in German. All other flavors work.

**Comment by nidhaloff** [comment]
@Zethson thanks for opening the issue. With "no longer translating", do you mean that it worked with previous versions (e.g v1.7.0)?

**Comment by Zethson** [comment]
Yes exactly. Sorry, should have clarified this.

**Comment by nidhaloff** [comment]
@Zethson thanks for the feedback. Did you pass the source and target language as abbreviations? can you show me how you called the function

**Comment by nidhaloff** [comment]
it would probably work if you use abbreviations as source and target languages. I just merged a fix for this

**Comment by Zethson** [comment]
Sorry, here's the code: https://github.com/theislab/ehrapy/blob/development/tests/tools/nlp/test_translator.py
Pretty sure that we are using abbreviations already.

**Comment by nidhaloff** [comment]
@Zethson I think your problem is the way you are passing the arguments. It's hard to tell from the code you are providing.

 Anyway, this simple example works:

```
    l = LibreTranslator(source="en", target="de")
    res = l.translate("good")
```

or if you have an api_key and want to use it:

```
    l = LibreTranslator(api_key="your_key", source="en", target="de")
    res = l.translate("good")
```

these two code examples work fine
