### ISSUE TITLE
Get all supported languages by Translator

### ISSUE THREAD

**Issue by Huertas97** [nidhaloff/deep-translator#146]
* deep_translator version: 1.8.3
* Python version: 3.7.13
* Operating System: Ubuntu 18.04.5 LTS

### Description

I've tried the tutorial's code for getting the supported language by a Translator

```python

from deep_translator import GoogleTranslator
langs_dict = GoogleTranslator.get_supported_languages(as_dict=True)

```

 but an error rose up:

```python

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-28-6c9d99937b52>](https://localhost:8080/#) in <module>()
      1 from deep_translator import GoogleTranslator
----> 2 langs_dict = GoogleTranslator.get_supported_languages(as_dict=True)

TypeError: get_supported_languages() missing 1 required positional argument: 'self'

```

**Comment by drdoof2019** [comment]
+1

**Comment by khanYas786** [comment]
from deep_translator import GoogleTranslator
langs_dict = GoogleTranslator().get_supported_languages(as_dict=True)
This seems to have worked for me. Got the idea from https://stackoverflow.com/questions/49355163/translate-missing-1-required-positional-argument-text
