### ISSUE TITLE
`make install` doesn't work

### ISSUE THREAD

**Issue by yutkat** [nidhaloff/deep-translator#151]
* deep_translator version: 4379cbabd029515ea1cf0a162808c25534822727
* Python version: 3.10.5
* Operating System: ArchLinux

### Description

You have removed setup.py so `make install` doesn't work anymore.
I would like to update the commands.

https://github.com/nidhaloff/deep-translator/blob/master/Makefile#L82-L83

### What I Did

- `git clone https://github.com/nidhaloff/deep-translator`
- `make install`

**Comment by nidhaloff** [comment]
@yutkat thanks for noticing this. Yes `setup.py` has been substituted with `pyproject.toml`. Therefore, the `make install` command should be changed to `poetry install` or `pip install .`, which should work for any package anyway. 
Would you like to update it and make a PR?
