### ISSUE TITLE
bug: GoogleTranslator.translate_batch does not circumvent request limit

### ISSUE THREAD

**Issue by chbridges** [nidhaloff/deep-translator#154]
* deep_translator version: 1.8.3
* Python version: 3.10.4
* Operating System: macOS 12.5

### Description

deep_translator.exceptions.TooManyRequests: Server Error: You made too many requests to the server. According to google, you are allowed to make 5 requests per second and up to 200k requests per day. You can wait and try again later or you can try the translate_batch function

It appears that the translate_batch function simply calls the translate function for each element in the passed iterable, still resulting in 1 request per element. This is not what the error message implies and using translate_batch therefore does not solve this issue in any way.

### What I Did

Run translate_batch several times with lists of about 2000 texts.

**Comment by libialany** [comment]
Could you provide a sample of the text?
Can you time it?
I tried with a list of 50 texts and it took 16sec.
- deep_translator version: 1.9.2
- Python version: 3.10.6
- Operating System: Linux

my sample:
https://paste.me/paste/e3022dba-3e86-4d93-6e38-6e18411d9f63#54c78453e5f7f961bcd52fe5584405850dfc360c8c4f4b4bf9c354cc93950c37
