### ISSUE TITLE
ModuleNotFoundError: No module named 'deep_translator'

### ISSUE THREAD

**Issue by Rivow** [nidhaloff/deep-translator#157]
* deep_translator version:1.8.5
* Python version: 3.7
* Operating System: Windows

### Description

I have been using this library for weeks with no problem. But suddenly today I get an error ModuleNotFoundError: No module named 'deep_translator' even though yesterday it worked fine does anyone have a solution?

**Comment by crobledolete** [comment]
I had the same problem this morning. A quick solution for me was to downgrade the version of the package to v1.8.3.

I think this trouble is related to the newest version released (v1.8.5). If you go to its pip documentation (https://pypi.org/project/deep-translator/) you won't see any post or documentation related to this lastest version, which seems a bit strange imo.

**Comment by Rivow** [comment]
Thanks so much that fixed it. I was struggling to find any info on new version but couldn't find any so I just assumed I did something wrong but thanks so much for the help

**Comment by jkempinger-khc** [comment]
Is this issue actually resolved/completed?  I still see v1.8.5 on PyPI, even though there's no release newer than v1.8.3 here.

**Comment by gavingosling** [comment]
I don't believe this is resolved either, however pinning the version to 1.8.3 worked for me.
