### ISSUE TITLE
using certain cuda in multi gpu environment?

### ISSUE THREAD

**Issue by Marcophono2** [nidhaloff/deep-translator#174]
Hello!

As my nvidia-smi monitor displays an increase in gpu usage when making a translation it seems that deep-translator is using cuda, if available. But I have three graphic cards and due to performance reasons I need to use always the related gpu. Is it possible to influence this?

**Comment by nidhaloff** [comment]
@Marcophono2 Hi, Can you please provide more context? deep-translator does not use cuda!

**Comment by Marcophono2** [comment]
Thanx @nidhaloff , that is the answer. :-)
