### ISSUE TITLE
Transcription of the translated words

### ISSUE THREAD

**Issue by a1exjane** [nidhaloff/deep-translator#180]
Hello Nidhal. Please tell me how can i get latin letters transcription of translated words?

**Comment by NicholasBarrett98** [comment]
Perhaps it is better to ask for a professional translation.

**Comment by nidhaloff** [comment]
@a1exjane Can you provide more information? maybe an example of what you are trying to achieve

**Comment by a1exjane** [comment]
For example: If you translate any word in google translator, you can see tranlation and lower transcription. Please tell me if you know, how can I get the transcription.
![изображение](https://user-images.githubusercontent.com/50675919/215251657-83d6ba35-88ad-490f-9b7c-6926f999cf1a.png)

**Comment by nidhaloff** [comment]
@a1exjane I see. Unfortunately, this is not possible with deep-translator since the package uses a different API than the official google translate.
