### ISSUE TITLE
Translating documents

### ISSUE THREAD

**Issue by MKatereggaExigent** [nidhaloff/deep-translator#183]
Are there any plans of adding a feature that translates and preserves the structure of documents?

```
I have about 500 pdfs that I need to translate to English but I don't want to first convert them to text since I need to preserve their structure.
```

**Comment by bleriot14** [comment]
> Are there any plans of adding a feature that translates and preserves the structure of documents?
> 
> ```
> I have about 500 pdfs that I need to translate to English but I don't want to first convert them to text since I need to preserve their structure.
> ```

Did you find any solution for this ? Can you please share it ?
