### ISSUE TITLE
SSL Certification Error

### ISSUE THREAD

**Issue by souravkrpathak** [nidhaloff/deep-translator#185]
* deep_translator version: 1.9.1
* Python version: 3.9
* Operating System: Win 11

### Description

Error: 
ERROR out: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /m?tl=pt&sl=en&q=my+name+is+python(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))

My Code:
from deep_translator import GoogleTranslator
translator = GoogleTranslator(source='en', target='pt')
data = 'my name is python'
translator.translate(data)

```

**Comment by nidhaloff** [comment]
@souravkrpathak This looks like an issue with your system. It is not related to deep-translator. 
Make sure that your system is configured correctly, you can find many examples about this error online.

I guess, I can allow arguments to be passed to deep-translator under the hood as a hack (specifically the verify=False argument), but this is not a good idea for security reasons. So the best option would be from your side to verify your configuration.

**Comment by souravkrpathak** [comment]
Thanks @nidhaloff for your response
