### ISSUE TITLE
suggestion to add timeout parameter to requests

### ISSUE THREAD

**Issue by suqingdong** [nidhaloff/deep-translator#186]
nice project!

It is recommended to add `timeout` parameter to `requests.get` or `requests.post`.

**Comment by nidhaloff** [comment]
Hey @suqingdong Thanks for the feedback. Would you like to do it and open a PR?

**Comment by suqingdong** [comment]
> Hey @suqingdong Thanks for the feedback. Would you like to do it and open a PR?

Oh, I found a method to set `timeout` globally, so there is no need to change this project:
```python
import functools
import requests

timeout = 5
for method in ('get', 'post'):
    func = getattr(requests, method)
    setattr(requests, method, functools.partial(func, timeout=timeout))

# calling translate ...
```

**Comment by pmaoui** [comment]
Closing this issue is not a good idea as monkey patching the global requests module is far from being a good idea. A default value (5 or 10 sec ?) that can be overwritten through params should be the way to go IMO.
