### ISSUE TITLE
suggestions for famous translators that you would like to have in the deep_translator

### ISSUE THREAD

**Issue by nidhaloff** [nidhaloff/deep-translator#20]
### Description

I'm opening this thread to discuss the possibility to integrate more translators. We can discuss here which famous translators you want to have in this tool. Why and which translators are you using the most and whether you have ideas to improve the project.

**Comment by foubou** [comment]
Hi, congratulations for this tool, and thank you for your hard work!
I wanted to know if your program allows to translate automatically a XLS sheet with DeepL? (I have an API key).
I need something like that : https://www.excel-text-translator.com/index.html
Thank you for your reply!

**Comment by nidhaloff** [comment]
@foubou Thanks for your words ;). There is (at the moment) no function to translate XLS files. However, implementing this is not complex. If you read the file with a tool like [Pandas](https://pandas.pydata.org/) and parse the values in the specific column you want to translate to a text array, then it should be easy to automate the translations using the deep-translator. 

I'm very busy at the moment and I have no time to work on this (sorry), but maybe someone else would like to work on this enhancement. I will let the issue open in order to get noticed by new contributors (or you).

@prataffel @senk8 If you like you can work on this feature ;)

**Comment by devrobgilb** [comment]
Just found this tool; it was exactly what I was looking for. I would suggest adding Microsoft, Amazon, and Yarakuzen. I haven't found really any good python libraries that make it easy to work with Microsoft.

**Comment by nidhaloff** [comment]
@devrobgilb Thank you. I will check it out when I have more time :/ 

I hope someone can contribute if they have more time

**Comment by nidhaloff** [comment]
@devrobgilb Microsoft translator can now be used ;)

**Comment by devrobgilb** [comment]
> @devrobgilb Microsoft translator can now be used ;) version >= 1.3.5

That's fantastic! Thanks for the work!

**Comment by juligreen** [comment]
papago might be interesting: https://papago.naver.com/

**Comment by nothead31** [comment]
@foubou If you could open a separate ticket for your suggestion, I already work in Pandas and can tackle adding that in later after I finish my current work.

**Comment by debjyoti003** [comment]
@nidhaloff If you want, I can work on the requirement mentioned by @foubou.

**Comment by nothead31** [comment]
> @nidhaloff If you want, I can work on the requirement mentioned by @foubou, even in my system I have added that requirement.

Please reference Issue#63

**Comment by debjyoti003** [comment]
@nothead31 I have added that feature and send a pull request. Please check that out.

**Comment by cosmo4412** [comment]
I would suggest adding more tools like Opus-mt from Helsinki NLP[https://huggingface.co/Helsinki-NLP](url) , Mbart [https://huggingface.co/transformers/model_doc/mbart.html](url) , and m2m_100 from Facebook Research[https://github.com/UKPLab/EasyNMT](url)

**Comment by nothead31** [comment]
@cosmo4412 I fixed your links, remember that markdown uses the `(link name)[link url]` format :)

As for your suggestion, the third link to EasyNMT looks like a machine learning system that runs off of the models you mentioned in the first two links. I'm not too familiar with machine learning myself, so I'll let you make the case why these would be beneficial to add to our project. From my perspective, EasyNMT looks a lot like an alternative to deep-translator with similar functionality (albeit approached from a different perspective) rather than something for us to integrate here.

**Comment by cosmo4412** [comment]
First of all thanks for pointing out my error regarding the format, I shall keep that in mind.
And secondly about my suggestion, my perspective here was to add support of more algorithms, which can help users compare the performance of different algorithms and choose the best one according to their needs.

**Comment by suliveevil** [comment]
Apple Translate on macOS.
