### ISSUE TITLE
Please add GPT-4 to the translators supported

### ISSUE THREAD

**Issue by Emasoft** [nidhaloff/deep-translator#203]
Please add GPT-4 to the supported translators
===================================
I recently compared the translations made by Google, DeepL and GPT-4. GPT-4 is astonishing better than the others. Way better.

An example:

Original Chinese Text (a quote from a classic Chinese novel):
=============================================

那年轻人看了我半晌，随后拔脚便往我屋里跑。他也把苦根摇了又摇，又将耳朵贴到苦根胸口听了很久，才说：

“听不到心跳。”

村里很多人都来了，我求他们都去看看苦根，他们都去摇摇，听听，完了对我说：

“死了。”

苦根是吃豆子撑死的，这孩子不是嘴馋，是我家太穷，村里谁家的孩子都过得比苦根好，就是豆子，苦根也是难得能吃上。我是老昏了头，给苦根煮了这么多豆子，我老得又笨又蠢，害死了苦根。

往后的日子我只能一个人过了，我总想着自己日子也不长了，谁知一过又过了这些年。我还是老样子，腰还是常常疼，眼睛还是花，我耳朵倒是很灵，村里人说话，我不看也能知道是谁在说。我是有时候想想伤心，有时候想想又很踏实，家里人全是我送的葬，全是我亲手埋的，到了有一天我腿一伸，也不用担心谁了。

Google Translation:
===============
The young man looked at me for a while, then ran to my room. He shook the bitter root again and again, put his ear to the bitter root's chest and listened for a long time before saying:

"I can't hear my heartbeat."

Many people from the village came, and I begged them all to go and see the bitter root, and they all went to shake it, listen to it, and said to me when they were done:

"died."

Kugen is fed to death by eating beans. This child is not greedy, but my family is too poor. The children in the village have a better life than Kugen. Even beans, Kugen is hard to eat. I was so old and dizzy that I boiled so many beans for Kugen. I was so old and stupid that I killed Kugen.

In the days to come, I can only live alone, and I always think that my days will not be long, who knows that these years will pass by. I am still the same, my waist still often hurts, my eyes are still blurry, but my ears are very good. When people in the village talk, I can know who is talking without looking. Sometimes I feel sad when I think about it, and sometimes I think about it and I am very down-to-earth. All the family members were buried by me, and I buried them all with my own hands. One day, when I stretch my legs, I don’t have to worry about anyone. 

DeepL Translation:
==============
The young man looked at me for a long time, then pulled his feet and ran to my house. He also shook the bitter root again and again, and put his ear to the bitter root chest to listen for a long time, before saying.

"I can't hear a heartbeat."

Many people in the village came, I begged them all to see the bitter root, they all went to shake, listen, finished to me and said.

"Dead."

Bitter root is eating beans to die, the child is not greedy, is my family is too poor, the village who's children are better off than bitter root, is the beans, bitter root is also rare to eat. I was too old to cook so many beans for Bitterroot, I was too old and stupid to kill Bitterroot.

I can only live alone in the days to come, I always thought I would not have long to live, but who knows, once again after these years. I still look the same, my back still hurts a lot, my eyes are still blurry, but my ears are very good, the village people talk, I can know who is talking without looking. Sometimes I think about sadness, sometimes I think about it and very solid, the family is all my burial, all my hands buried, to one day I stretch my legs, and do not have to worry about who. 

And here is the ChatGPT-4 translation:
=============================
The young man looked at me for a while and then ran into my house. He also shook Kugen and put his ear to Kugen's chest for a long time before saying:

"I can't hear a heartbeat."

Many people from the village came and I asked them to go and see Kugen. They all went to shake him and listen, then they said to me:

"He's dead."

Kugen died from eating too many beans. The child was not greedy, but my family was too poor. The children in other families in the village lived better than Kugen. Even beans were rare for him to eat. I was old and confused when I cooked so many beans for Kugen. I was old, clumsy and stupid, and killed Kugen.

In the days that followed, I could only live alone. I always thought that my days were not long either, but who knew that these years had passed one after another. I am still the same as before: my waist often hurts; my eyes are still blurry; but my ears are very sharp - when people in the village talk, I can tell who is speaking without looking. Sometimes when I think about it, it makes me sad; sometimes when I think about it again, it feels very hard - all the people in my family were buried by me personally. When one day my legs stretch out (I die), there will be no need to worry about anyone anymore.

**Comment by nidhaloff** [comment]
Hi, sorry for the late reply. This is a good idea, I would like to add this feature asap. 
It may take some time because I'm very busy lately, but I will take a look at it asap. If someone wants to work on this, it would be great too. I added some labels to make this issue easy to find.
Thanks!
