### ISSUE TITLE
Help! I cannot install the AI attachment for deep translator in pip3

### ISSUE THREAD

**Issue by xuckless** [nidhaloff/deep-translator#223]
* deep_translator version: 1.11.4
* Python version: 3.9.6
* Operating System: Mac OS 13.4.1 (c) (22F770820d)
* pip version: 23.2

### Description

I cannot install the ai support for deep-translator as displayed in the [documentation](https://deep-translator.readthedocs.io/en/latest/README.html#chatgpt-translator). I am new to coding, so I might have messed the process up somewhere, please help. 

### What I Did

I ran the command with pip3 instead of the normal pip in the documentation on my Mac terminal. 

The command I ran in Terminal:
```
$ pip3 install deep-translator[ai]
```

Output: 
```
zsh: no matches found: deep-translator[ai]
```

I am also adding python traceback from the python code that I ran:
```
Traceback (most recent call last):
  File "/Users/a/personal-projects/mtl/translate.py", line 26, in <module>
    translate = ChatGptTranslator(api_key='key-hidden', target='english').translate(content)
  File "/Users/a/Library/Python/3.9/lib/python/site-packages/deep_translator/chatgpt.py", line 43, in translate
    import openai
ModuleNotFoundError: No module named 'openai'
```

**Comment by xuckless** [comment]
Update:

Not only AI, I cannot install any attachments (docx, pdf) in pip3. All the commands are returning the same aforementioned output.

Inputs:
```
$ pip3 install deep-translator[docx]
$ pip3 install deep-translator[pdf]
```

Outputs:
```
zsh: no matches found: deep-translator[docx]
zsh: no matches found: deep-translator[pdf]
```

**Comment by nidhaloff** [comment]
@xuckless I think this is related to the type of shell you are using (which is zsh in this case), Just try to add quotes `pip3 install 'deep-translator[ai]'`

**Comment by xuckless** [comment]
Thankyou for your help! It works now.
