### ISSUE TITLE
How to add multiple http proxy addresses？

### ISSUE THREAD

**Issue by xukai504087493** [nidhaloff/deep-translator#225]
How to add multiple http proxy addresses？
such as: 
    
proxies_example = {
    "https": "192.168.1.2:2000",
    "http": "192.168.1.2:2000"}

 proxies_example = {
    "https": "192.168.1.3:3000",
    "http": "192.168.1.3:3000"}

In case a proxy cannot access, another proxy can be used instead.

Thanks a lot!

**Comment by Arsh1219** [comment]
you can simply use for loop to try all proxies one by one.

**Comment by nidhaloff** [comment]
Hi, I would say use a for loop.
