### ISSUE TITLE
extend the docs

### ISSUE THREAD

**Issue by nidhaloff** [nidhaloff/deep-translator#23]
### Description

extend and improve the docs

**Comment by devrobgilb** [comment]
I would be interested in helping out with this a bit if you could give me some specific things that could be done.

**Comment by nidhaloff** [comment]
@devrobgilb thanks for joining ;) you can check the docs in the docs folder. There you will find everything. you can just be creative and improve things in the docs. You can even use another template that will look better. I'm using sphinx to generate docs, if you don't  know what that is, you may want to have a basic idea first but that should be straightforward. Also check this [link](https://sphinx-themes.org/) for the templates
