### ISSUE TITLE
Can I use deep_translator offline?

### ISSUE THREAD

**Issue by SoftologyPro** [nidhaloff/deep-translator#233]
Is there any way to cache translation models so I can use deep_translate offline without any Internet connection?
Do any of the supported translator services have a way to cache their models locally for this purpose?

**Comment by shanchuantian** [comment]
To my knowledge, argos-translate supports offline translation.

**Comment by Benadictus** [comment]
Deep is not "a translator program"  It is a **management** program for **other** actual translator systems.
These systems are all online, eg: Google, ChatGPT.   The online translation systems all have vast libraries (petabytes) of english and `other` languages and large code bases to carry out the actual translation.

So no.

**Comment by nidhaloff** [comment]
Hi, short answer is no, you cannot use it offline (at least for now)
