### ISSUE TITLE
error Translation with DeepL as Translator

### ISSUE THREAD

**Issue by Askadelion** [nidhaloff/deep-translator#24]
* deep_translator version: 1.3.0 
* Python version: 3x
* Operating System: Win10

### Description

I have try to use DeepL (i have an api_key) in ur script but i become an error,
i have use follow commands

```
translated = DeepL("MYKEY").translate("keep it up, you are awesome")
print(translated)
```

### What I Did

```
Traceback (most recent call last):
  File "test_deepl.py", line 5, in <module>
    translated = DeepL("KEY").translate("keep it up, you are awesome")
  File "C:\Python37-32\lib\site-packages\deep_translator\deepl.py", line 23, in __init__
    self.__base_url = BASE_URLS.get("DEEPL").format(version=self.version)
IndexError: tuple index out of range
```

**Comment by nidhaloff** [comment]
@Askadelion Thanks for noticing this. This was a bug in the constructor, I made a fix attempt. Check out the new version 0.3.1. 

I will close the issue but feel free to re-open if you are having problems with this
