### ISSUE TITLE
Linguee Translator does not support all languages

### ISSUE THREAD

**Issue by fotisskal** [nidhaloff/deep-translator#27]
* deep_translator version: Latest
* Python version: 3.8
* Operating System: Ubuntu

### Description

Linguee Translator does not support all languages in LINGUEE_LANGUAGES_TO_CODES. For example in the case of translating from Greek to English, I get `Required element was not found in the API response` error.

**Comment by nidhaloff** [comment]
@fotisskal  yes it looks like linguee does support translation from English to greek but not the other way around
