### ISSUE TITLE
Not translate some words / html tags

### ISSUE THREAD

**Issue by gleidsonh** [nidhaloff/deep-translator#29]
Is there a way to not translate some words? For example, I am translating html, but tags like < strong > are translated as well.

I could remove the tags and translate only the text, but in some cases tags are important. For example, "Eu quero < strong > comprar < /strong > um carro" (portuguese), if you are going to translate separately "Eu quero", "comprar", "um carro", translation will be different than translating it entirely.

For example, the translated phrase "I want to buy a car", "I want to" would be "I want", not being correct when putting everything back together: "I want buy a car". Translating with html tags this problem does not happen. [Look here](https://translate.google.com/?sl=pt&tl=en&text=%3Cp%3EEu%20quero%3Cstrong%3Ecomprar%3C%2Fstrong%3Eum%20carro%3C%2Fp%3E&op=translate).

So I ask: is it possible not to translate some words, or is it at least possible to do this with html tags?

**Comment by nidhaloff** [comment]
@gleidsonh can you show the code you used to translate this sentence?

**Comment by nidhaloff** [comment]
@gleidsonh I'm closing the issue since there was no feedback from you
