### ISSUE TITLE
What is there a limit of 5000 characters in BaseTranslator?

### ISSUE THREAD

**Issue by pmi123** [nidhaloff/deep-translator#30]
I am curious as to the reason for a 5,000 character max limit that you have hard coded into the BaseTranslator class. Did you arrive at this empirically, or do the different translation services impose this limit?

Thanks!

Mark

**Comment by nidhaloff** [comment]
Hey @pmi123 good question, this is because the google translator has a max limit chars check, which is 5000 characters. You can google about it to learn more
