### ISSUE TITLE
Keyerror: 'h1' when performing translations

### ISSUE THREAD

**Issue by yudhiesh** [nidhaloff/deep-translator#33]
* deep_translator version: 1.3.3
* Python version: 3.6
* Operating System: Google Colab

### Description
I have been using this script to translate words but just today it stopped working and I get this error:
`KeyError: 'hl'`

Full error:
![Screenshot 2021-02-13 at 1 06 25 AM](https://user-images.githubusercontent.com/55042754/107798908-b63ef280-6d97-11eb-9780-d83e8447ce1f.png)

```
from deep_translator import GoogleTranslator
from deep_translator import GoogleTranslator as GT
from deep_translator import exceptions as excp


def translate(x):
    try:
        v = GT(source='auto', target='en').translate(x['tweet_text']) if (x['tweet_text'] != " " and x['lang'] != "en") else x['tweet_text']
    except (excp.NotValidPayload, excp.NotValidLength) as e:
        v = f'Translation Exception: {type(e)}'
    return v

# translate the column
df_bdtu['translated'] = df_bdtu[['tweet_text', 'lang']].swifter.apply(lambda x: translate(x), axis = 1)
```

**Comment by nidhaloff** [comment]
@yudhiesh Thanks for opening the issue. Can you please provide the source and target language? and if possible the text that you wanted to translate? basically the value of x["tweet_text"] or something, just to have a reproducible example

**Comment by yudhiesh** [comment]
@nidhaloff source is set to "auto-detect" and target language is English. I can share a sample of the text as its the entire row of data.

```
{'lang': {1232: 'en',
  6581: 'en',
  6864: 'es',
  7040: 'und',
  7119: 'und',
  8654: 'es',
  9148: 'en',
  11690: 'en',
  11732: 'en',
  11914: 'en'},
 'tweet_text': {1232: 'Bukayo Saka I spoke to Laca before the game as soon as you get the ball Ill run in behind he listened I was really happy with that',
  6581: 'A legal battle is brewing over who gets to tax employees working from home across state lines',
  6864: 'A cronica do',
  7040: 'My 2020',
  7119: '',
  8654: 'VUELVE PRONTO',
  9148: 'IN MY OWN WORDS',
  11690: 'Done dealCape Town City have completed the signing of Justin Shonga from rivals Tshakhuma Tsha Madz',
  11732: 'One who is everywhere is nowhere Seneca',
  11914: 'We cant depend on youts Arsenal 00 Crystal Palace Join P'}}
```

**Comment by yudhiesh** [comment]
@nidhaloff downgrading to 1.3.2 works

**Comment by nidhaloff** [comment]
@yudhiesh Thanks for the feedback. Yeah I thought immediately that 1.3.2 would work. I did a quick deployment yesterday without an extensive test, which is clearly a problem. This will be solved permanently in the next version 1.3.4

I will close this now but feel free to re-open it if you are having this issue in the future

**Comment by yudhiesh** [comment]
@nidhaloff I am getting another error now regarding my connection
```
deep_translator.exceptions.RequestError: Request exception can happen due to an api connection error. Please check your connection and try again
```

**Comment by nidhaloff** [comment]
@yudhiesh are you sure that it is not related to internet problems?

**Comment by yudhiesh** [comment]
@nidhaloff I restarted my runtime and the translations were successful. Thanks for the help and the great library.

**Comment by nihaalnz** [comment]
I once ran into this error and was able to get rid of it by making sure source and target languages are never same.

**Comment by nidhaloff** [comment]
@nihaalnz  which version? 1.3.8?

**Comment by nihaalnz** [comment]
@nidhaloff Yep, new version too.

**Comment by nidhaloff** [comment]
@nihaalnz you are right. I will catch this in the next version
