### ISSUE TITLE
NotValidLength - 5000 chars limit?

### ISSUE THREAD

**Issue by credo99** [nidhaloff/deep-translator#37]
Hi,

Is it possible to split a txt file in 5000 chars batches and submit them to google for translation? I suppose this error comes from this limit..
Thanks

* deep_translator version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by nidhaloff** [comment]
@credo99 which error?

**Comment by nidhaloff** [comment]
@credo99 you didnt post any error,  I don't understand your question
