### ISSUE TITLE
deep_translator does not translate text in few languages

### ISSUE THREAD

**Issue by lenovo360** [nidhaloff/deep-translator#39]
deep_translator does not translate text properly in a few languages.

Here's my code:

```
from deep_translator import GoogleTranslator

translator = GoogleTranslator(target="irish")

text_to_translate = "Hello, how are you?"

translated_text = translator.translate(text_to_translate)

print(translated_text)
```

Here when I run the code, the output is the same and the text does not seem to get translated.

I tried adding the `source` parameter to the `GoogleTranslator` class, but the output is still the same.

Can you please help me in fixing this problem?

Deep_translator version: 1.3.5
Python version: 3.9.1
OS: Windows 10

**Comment by nidhaloff** [comment]
@lenovo360 I fixed this in the latest version 1.3.6
