### ISSUE TITLE
Can't translate 2000+ words from a text file - character limit?

### ISSUE THREAD

**Issue by vardecab** [nidhaloff/deep-translator#40]
* deep_translator version: 1.3.9
* Python version: 3.7.4
* Operating System: Windows 10

### Description

Hi! :)

I wanted to translate 2000+ words from a text file but when running: 
```python
translated = GoogleTranslator(source=select_source_language, target=select_target_language).translate_file("file.txt")
```
I got an error: 
```python
raise NotValidLength(payload, min_chars, max_chars)
```
with `Text length need to be between 1 and 5000 characters`.

It was working fine when I ran the code on 200+ words, though. 

Does this package have a character limit then? If so, is there any workaround?

**Comment by nidhaloff** [comment]
@vardecab hmm I'm guessing you have too many spaces in your files, which makes the algorithm thinks that there are more than 5k characters. Can you check that up?

I should have catched this behavior already!

**Comment by nidhaloff** [comment]
@vardecab Can you try upgrading to 1.4.0 ?

**Comment by vardecab** [comment]
> @vardecab Can you try upgrading to 1.4.0 ?

I did, same error is happening but...

> I'm guessing you have too many spaces in your files, which makes the algorithm thinks that there are more than 5k characters.

I have a file with ~ 2000 words (~ 19k characters) which is way over 5k characters you've mentioned. They are stored line by line as seen here:
![Code_QmTQszgaj0](https://user-images.githubusercontent.com/6877391/110246450-ee38f000-7f67-11eb-96cb-959e7796b9a0.png)
Does it mean that I cannot have more than 5k characters in the file I'm passing to `translate_file()`?

**Comment by nidhaloff** [comment]
@vardecab Exactly, you can pass more than 5k characters. This is a restriction from google translate not deep-translator.

You can use the translate_batch for this task ;)

**Comment by vardecab** [comment]
FYI `translate_batch()` also has a character limit. To get around it one needs to split a `list` into multiple smaller lists, eg:
```python
chunks = [original_words[x:x+250] for x in range(0, len(original_words), 250)] # split list into sublists of 250 words each
```
and then iterate through all.
