### ISSUE TITLE
Is there any way to speed up the process of translating bigger payloads?

### ISSUE THREAD

**Issue by vardecab** [nidhaloff/deep-translator#42]
* deep_translator version: 1.4.1
* Python version: 3.7.4
* Operating System: Windows 10

### Description

I'm wondering if there is any way to **speed up the process of translating bigger payloads** - hundreds, even thousands of words? 
> deep_translator sleeps for two seconds after each request in order to not spam the google server

That seems reasonable… but 250 words are gonna need 8+ minutes to process (250 words × 2 seconds = 500 seconds = 8.33 minutes). 

Having a payload of ~ 2500 words one would need to wait for ~ 83 minutes before script is executed in full. 

Can `deep-translator` wait for less than 2 seconds? Maybe 1 or even a fraction of a second to speed up the process?

**Comment by vardecab** [comment]
I ran a few tests with `sleep()` in `google_trans.py` changed from `(2)` to `(0.5)` seconds and payloads of ~ 250 words - it seems to work just fine.

```python
def translate_batch(self, batch=None):
        """
        translate a list of texts
        @param batch: list of texts you want to translate
        @return: list of translations
        """
        if not batch:
            raise Exception("Enter your text list that you want to translate")

        print("Please wait.. This may take a couple of seconds because deep_translator sleeps "
              "for two seconds after each request in order to not spam the google server.")
        arr = []
        for i, text in enumerate(batch):

            translated = self.translate(text)
            arr.append(translated)
            print("sentence number ", i+1, " has been translated successfully")
            # sleep(2)
            sleep(0.5)

        return arr
```

**Comment by vardecab** [comment]
It also worked fine with `sleep(0.15)` 🤔

```python
print(len(list)) # => 250
print(run_time) # => Script run time: 91.61 seconds. That's 1.53 minutes.
```

**Comment by vardecab** [comment]
I'm not translating sentences or paragraphs but just lots of single words. What you've said is probably a valid workaround but it feels more natural to just pass a list of original words and get translated words back from API. 

Doing this your way would mean that I need to join my words into strings and then split strings into words upon return from API which kinda is backwards logic.

**Comment by nidhaloff** [comment]
@vardecab  then join your list of words as a string and then split your translated result again and there you have it. Where is the problem?

**Comment by FrancescoDiCursi** [comment]
> * deep_translator version: 1.4.1
> * Python version: 3.7.4
> * Operating System: Windows 10
> 
> ### Description
> I'm wondering if there is any way to **speed up the process of translating bigger payloads** - hundreds, even thousands of words?
> 
> > deep_translator sleeps for two seconds after each request in order to not spam the google server
> 
> That seems reasonable… but 250 words are gonna need 8+ minutes to process (250 words × 2 seconds = 500 seconds = 8.33 minutes).
> 
> Having a payload of ~ 2500 words one would need to wait for ~ 83 minutes before script is executed in full.
> 
> Can `deep-translator` wait for less than 2 seconds? Maybe 1 or even a fraction of a second to speed up the process?

I've tried with chunks of words as "word1,word2,word3, ..." and this has the great problem that some terms are not translated (while they are translated if done on the single word) and most importantly chunks' lenght is not equal all the times (some translations simply disappear in the translated chunk).

Is anyone else facing these two problem with the chunk approach?
