### ISSUE TITLE
translate_batch() missing 2 required positional arguments: 'target' and 'batch'

### ISSUE THREAD

**Issue by msoutopico** [nidhaloff/deep-translator#44]
* deep_translator version: 1.4.1
* Python version: 3.9.1
* Operating System: macOS 10.13.6

### Description

my Python file has

```
from deep_translator import DeepL
api_key="xxxx"
texts = ["hallo welt", "guten morgen"]
translated = DeepL(api_key).translate_batch(texts)
```

### What I Did

I run the file as `python3 deepl.py`. The results are:

```
Traceback (most recent call last):
  File "/Users/souto/path/to/deepl.py", line 4, in <module>
    translated = DeepL(api_key).translate_batch(texts)
TypeError: translate_batch() missing 2 required positional arguments: 'target' and 'batch'
```

**Comment by nidhaloff** [comment]
@msoutopico Thanks for opening the issue ;) 

you are right! The example in the Readme is misleading.

`translated = DeepL(api_key).translate_batch("english", "german", texts)`

Let me know If it worked for you ;)
