### ISSUE TITLE
Proxy support?

### ISSUE THREAD

**Issue by SplitGemini** [nidhaloff/deep-translator#45]
* deep_translator version: 1.4.1
* Python version: 3.9
* Operating System: win10 20H2

### Description

Add a proxy argument to client to use a proxy connection.

### What I Did
Like this.
```python
GoogleTranslator(source='auto', target='de', proxies={'http':'http://localhost:1080'}).translate('I am a fool..')
```

**Comment by nidhaloff** [comment]
@SplitGemini I was very busy last days, but this is already on the todo list ;)

**Comment by G-Pavel** [comment]
Would be a great addition.
And please also add sock5 proxy support.

**Comment by nidhaloff** [comment]
@SplitGemini proxies integration is supported in the new version 1.4.2
