### ISSUE TITLE
deep_translator - GoogleTranslator does not translate German to Dutch directly.

### ISSUE THREAD

**Issue by arrabida** [nidhaloff/deep-translator#52]
deep_translator version: 1.4.2
Python version: 3.8.5
Operating System: Ubuntu 20.04

Problem: deep_translator - GoogleTtranslator does not translate German to Dutch directly.

I need to translate first to English and than from English to Dutch.
Translate from German to other languages than Dutch is no problem.

To reproduce:
```
from deep_translator import GoogleTranslator
description = "Zwei minimale Dellchen auf der Rückseite."
translated_text = GoogleTranslator(source='de', target='nl').translate(description)
```

the output gives a translated text in English instead of Dutch.
gives "Two minimal dents on the back." instead of "Twee minimale deukjes op de achterkant."

**Comment by Duncanr-glitch** [comment]
I haven't found source of the bug in the code yet, but trying this out, it seems the same issue can be reproduced if you change the source language to any language (or no language) and then make the target language dutch/nl.

**Comment by nidhaloff** [comment]
@Duncanr-glitch Yes, this seems to be an issue when translating to dutch/nl in general. I have not found the source of the bug too

**Comment by nothead31** [comment]
@nidhaloff is it possible this issue is related to #86 ?
