### ISSUE TITLE
How to use DeepL Api Free?

### ISSUE THREAD

**Issue by neoryd** [nidhaloff/deep-translator#55]
Hello I saw the new update, it includes a deepL free api but there's no instruction how to use it. Plss help

**Comment by nidhaloff** [comment]
@neoryd Hi, you will need to register and log in to your deepl account, where you will find your api key. If you have the api key then check the docs and you will see some examples on how to use it. 

PS: deep-translator uses the deepl free api by default in version > 1.4.2
