### ISSUE TITLE
.translate(source=/target=) vs .__init__(source=/target=)

### ISSUE THREAD

**Issue by prof-milki** [nidhaloff/deep-translator#56]
> * type: informational
> * priority: low
> * severity: none
> * deep_translator version: 1.4.3
> * Python version: 2.7 / 3.8
> * Operating System: Linux

So, I'm currently integrating some deep-translator backends with [PageTranslate](https://fossil.include-once.org/pagetranslate/) (a LibreOffice plugin). There's some overlap, and generally the API fits well. There's a few things I stumbled across however:

  * The `"DEEPL_FREE"` url in `constants.py` is missing a trailing slash. Probably also the `/v2/` according to the API docs. (Albeit my API key isn't working, haven't tested any of this.)

  * Between Pons/Linguee and Qcri/Yandex there's a bit of inconsistency to initializing things. Namely the source=/target= parameter, which either goes along with the `.translate()` call, or with the class `__init__()`. I feel like that should be on the class constructor in any case (like the DeepL translator does). Else, you end up with currying if you want to switch between backends.

    For example [translationbackends.py](https://fossil.include-once.org/pagetranslate/file/pythonpath/translationbackends.py):
    ```
        elif re.search("pons", backend, re.I):
            self.translate = self.from_words(
                deep_translator.PonsTranslator(source=source, target=target).translate
            )
        elif re.search("QCRI", backend, re.I):
            self.translate = functools.partial(
                deep_translator.QCRI(params["api_key"]).translate, source=source, target=target
            )
    ```

 * The dictionary .translate() function might also be worth renaming/splitting up. Perhaps a general convenience wrapper to simulate text translations through the word-by-word interface might be worthwhile.

 * Now for my use case, I probably need to bundle deep-translator. Which comes with a hefty price tag, since beatifulsoup pulls in lxml - thus bloating a LibreOffice extension from a few KB to 20MB. (And that's not even cross-platform).
  
    Obviously there's some convenience in BS4. Though if feasible, it would be nice if that could be optionalized/omitted for some translation backends. If it's really just grepping from some HTML tags, and only concerns the dictionary translators, there are leaner options.  

    Again, might not be feasible or worth the time. And after all that's just a downstream concern. And I'm still contemplating if importing just a singular class `from deep_translator import Yandex` avoids pulling in the other dependencies. (Also doesn't really matter for OpenOffice, since D-L won't run in that Python environment regardless. Only a worry for the LibreOffice bundle.).

 * Another more practical concern: `source="auto"` should be implicitly supported by D-L, regardless of the translation service. If there's no provider support then deep-translator should run an implicit language detection. (Btw, [langdetect](https://pypi.org/project/langdetect/) is still a functional alternative to the proprietary online service.)

**Comment by nidhaloff** [comment]
@prof-milki Thank you for these hints ;) Indeed there are inconsistencies in the code as you said! I didn't notice this until now. It's great that you noticed this. I will check it out asap.

You are also right about deepl I guess. The deepl docs are really bad (IMO), I couldn't figure out how to talk to their API. I couldn't test it too since I don't have an API. I guess I hoped that a user will eventually test it and give me some feedback.

 Now for your hint about Bs4, like you said I'm also not sure if it is feasible, worth investigating or how much time consuming would it be. If it seems to be a concern for many users then maybe we should investigate more. I will let this issue open for further discussions about the topic.

**Comment by prof-milki** [comment]
@nidhaloff Thanks for the feedback!
As for the API, that's probably more of a long-term consideration. You might have/want to introduce `**kwargs` or optional parameters, so either invocation works / it doesn't break existing users. (I've just been contemplating how I would get my project to match up. Or at least have matching source/target= parameters.)

> You are also right about deepl I guess. The deepl docs are really bad (IMO), I couldn't figure out how to talk to their API. I couldn't test it too since I don't have an API. I guess I hoped that a user will eventually test it and give me some feedback.

Well, I can quickly confirm that it's indeed working. But it really does require `self._DeepL__base_url = 'https://api-free.deepl.com/v2/'` with the `/v2/` suffix. Haven't tested the Pro API of course. But I wouldn't believe there's a reason for it to behave any differently.

> Now for your hint about Bs4, like you said I'm also not sure if it is feasible, worth investigating or how much time consuming would it be. 

I think this might be redundant. Not entirely sure how, but it was BS4 that somehow pulled in lxml for me. But since this is not a dependency of D-T itself (only requires Pythons builtin html.parser), it also ceases to be relevant. A manual wheel cleanup should fix this for my packaging process.

**Comment by nidhaloff** [comment]
@prof-milki Actually I'm already using optional parameters. Where do you suggest adding them exactly?

I will fix the deepl free URL asap ;)

**Comment by nidhaloff** [comment]
@prof-milki I applied some fixes in the actual version. I will close the issue now but feel free to re-open or give me feedback anytime ;) thanks again
