### ISSUE TITLE
Inviting contributors/maintainer(s) to the project

### ISSUE THREAD

**Issue by nidhaloff** [nidhaloff/deep-translator#58]
Hello everyone, 

First of all, I want to take a moment to thank all contributors and people who supported this project in any way ;) you are awesome!

The deep-translator package contains now 9 famous translators, which can be used simply just by importing the right one. I tried to keep the API very simple and as consistent as it can be, which will hopefully make contributors' lives easier if they want to implement/add a new translator to the chain. 

If you like the project and have any interest in contributing, you can contact me here or send me a msg privately:
- Email: nidhalbacc@gmail.com

**Comment by sou-joshi** [comment]
Great tool! Can find sometime to contribute. Amazon translator maybe 👍

**Comment by nidhaloff** [comment]
@sou-joshi Good idea, just go for it ;) I would happily review your PR

**Comment by nidhaloff** [comment]
Hi @singhaditya28 thanks for the info, but how can I do that?

**Comment by singhaditya28** [comment]
Go to --> hacktoberfest.digitalocean.com 
Then click start hacking, register yourself as a maintainer and provide the required details.

**Comment by singhaditya28** [comment]
@nidhaloff Did you get it?

**Comment by Dani-Google** [comment]
# Hi Nidal
I just tried Deep translator and loved it.
Although I'm new to Github but would love to contribute
Thank you for creating an Amazing tool :)

-Dani

**Comment by Dani-Google** [comment]
Hi **Nidal**
**I just tried Deep translator and loved it.**
Although I'm new to Github but **would love to contribute**
Thank you for creating an Amazing tool :)

**Comment by Dani-Google** [comment]
Hi **Nidhal**
I just tried **Deep translator** and loved it.
Although I'm new to Github but **would love to contribute**
**Thank you for creating an Amazing tool :)**

**Comment by rishi-kai21** [comment]
Hi @nidhaloff I would like to contribute to your project. Please let me know how I can assist you :)

**Comment by LordUbuntu** [comment]
I'm not sure how I can hep but I would _love_ to contribute, so count me in!

**Comment by nidhaloff** [comment]
@LordUbuntu @rishi-kai21 @Dani-Google Thanks, please take a look at the issues page and see what you can work on/improve. If you have any specific question, you can ask there.

**Comment by wchung42** [comment]
I'm new to open-source contribution but I would love to help in anyway.

**Comment by libialany** [comment]
I love to contribute, so count me in.
