### ISSUE TITLE
Error : Can't translate if text is less than 5k characters.

### ISSUE THREAD

**Issue by debjyoti003** [nidhaloff/deep-translator#61]
deep_translator.exceptions.NotValidPayload: {'text': 'some_text'} --> text must be a valid text with maximum 5000 character, otherwise it cannot be translated.

I am getting this error while I am trying to translate. Why is this issue happening, what should I do to solve this, please suggest me something.

**Comment by nidhaloff** [comment]
@debjyoti003 Hi, well as the error shows: your input must be a **valid text**. I think you are trying to pass a dictionary `{'text': 'some_text'}`. Try and convert that to string/text first as the error said. 

**example:**
if your dictionary is declared like this: `d = {'text': 'some_text'}`, then pass `d["text"] `to the translation function

**Comment by debjyoti003** [comment]
@nidhaloff but I am testing this on postman, and I am passing this as a json data, so how should I do it then, as API only takes json data right?

**Comment by nidhaloff** [comment]
how are you testing this? it's very hard to tell without seeing any code. Can you please post an example and show how you are using it
