### ISSUE TITLE
DEEPL integration 

### ISSUE THREAD

**Issue by foubou** [nidhaloff/deep-translator#63]
@nothead31

> If` you could open a separate ticket for your suggestion, I already work in Pandas and can tackle adding that in later after I finish my current work.

Hi nothead31 !
I will be great to have a DeepL integration in XLS files so that I can translate automatically multiple cells at once.
And what if I want DeepL to be working online with Google Sheets ? Do you think it can be done ?

Thank you very much for you answer and for help !

**Comment by nothead31** [comment]
@debjyoti003 If you want to submit a pull request for this issue, feel free to send it over. Since it's definitely something that will be worked on, it's been moved to its own issue.

**Comment by nothead31** [comment]
@foubou do you have an .xls document with sample data to test with? Preferably specify in the document or in your comment which languages need to be translated from/to.

**Comment by svshivapuja** [comment]
Hi is this issue still open ?

**Comment by nothead31** [comment]
Yes, it is.
