### ISSUE TITLE
papago might be interesting: https://papago.naver.com/

### ISSUE THREAD

**Issue by nothead31** [nidhaloff/deep-translator#67]
papago might be interesting: https://papago.naver.com/

_Originally posted by @juligreen in https://github.com/nidhaloff/deep-translator/issues/20#issuecomment-840664606_

**Comment by nidhaloff** [comment]
@nothead31 The latest version of deep-translator has already support for the Papago translator. 
https://github.com/nidhaloff/deep-translator/blob/master/deep_translator/papago.py

**Comment by nothead31** [comment]
I thought it was but must have had a brain fart when I looked for it.
