### ISSUE TITLE
[Feature Request] make library api more homogeneous 

### ISSUE THREAD

**Issue by fcolecumberri** [nidhaloff/deep-translator#69]
* deep_translator version: 1.4.4
* Python version: 3.9.5
* Operating System: Linux

I am trying to run this:

```python
#! /usr/bin/python3

from deep_translator import (
    GoogleTranslator,
    MicrosoftTranslator,
    PonsTranslator,
    LingueeTranslator,
    MyMemoryTranslator,
    YandexTranslator,
    DeepL,
    QCRI
)

translators = [
    GoogleTranslator,
    MicrosoftTranslator,
    PonsTranslator,
    LingueeTranslator,
    MyMemoryTranslator,
    YandexTranslator,
    DeepL,
    QCRI
]

if __name__ == '__main__':
    for translator_t in translators:
        try:
            print(translator_t)
            print(translator_t.get_supported_languages())
        except Exception as e:
            print(e)

```

And I find that some of the back-ends like `YandexTranslator`, `DeepL` & `QCRI` have not implemented the `get_supported_languages()` function (or at least not as a static function, `YandexTranslator` & `QCRI` have it as a non static)

This could be neat for people trying to find out which back-ends are useful for a given situation.

**Comment by nothead31** [comment]
Feel free to submit a pull request if you'd like to fix it. Meanwhile, you can use a workaround by importing [Click and using clirunner](https://click.palletsprojects.com/en/7.x/api/#click.testing.CliRunner) to invoke the command line directly from your own module. [More info on clirunner can be found here](https://click.palletsprojects.com/en/7.x/testing/)

**Comment by nidhaloff** [comment]
already done in https://github.com/nidhaloff/deep-translator/commit/186e33e46d447c79b2dcd86abe194ee14df29e67
