### ISSUE TITLE
Let's interop with js and python

### ISSUE THREAD

**Issue by vitonsky** [nidhaloff/deep-translator#78]
Hi, i found this project and its seems very good.

I make same project, but for javascript: https://github.com/translate-tools/core

What you think about to set links to each other in our projects? For example make section "Related projects" or "Alternatives for other languages" in `README.md` and insert there a link.

I think that cross linking to related projects will useful for all people who search tool for their case and programming language.

For example not so long ago i was can't found good translator for python and now maybe someone can't find free translator for javascript, but ended up in this repo or vice versa

**Comment by nothead31** [comment]
@nidhaloff has the final say, but I don't see much reason. A better solution would be building something akin to an awesome-list for translators, given the wide variety and large number of different tools in this category. That would allow a user looking for different translators to see several in an organized list format and compare them easily.

**Comment by vitonsky** [comment]
> @nidhaloff has the final say, but I don't see much reason. A better solution would be building something akin to an awesome-list for translators, given the wide variety and large number of different tools in this category. That would allow a user looking for different translators to see several in an organized list format and compare them easily.

I agree with you about awesome list, because it's very useful article format which reviews cool things, but i not sure about category which can contains our solutions. For awesome repo with only translators these list should be not small, but i don't know about really good tools for translate even on other programming languages.

I don't sure, but i think that all people use translators in js, python, and go, maybe in java. Do you know about more? Or maybe about other libraries on python/js which work well. If yes, please, write it here and maybe i make awesome list in project https://github.com/translate-tools and will maintenance it. If no, then awesome list will too small and not effective, even if add solutions with machine translations (like [LibreTranslate](https://github.com/LibreTranslate/LibreTranslate)) and other things, which not only about "library for translate text with Google/Yandex/etc" but about translate generally

Or, if you know about exists awesome lists with relevant category, give link and let's push there our projects.

My purpose is make connect between translate libraries to make search of solutions more simply.

Awesome list for translators it's good idea, such as it may give us platform for getting actual information about translators, place for PR our solutions and it may improve speed of fixing bugs, when google or other service change algorithms, because we could get fixes from each other

**Comment by nidhaloff** [comment]
@vitonsky Hi, I totally agree with @nothead31
