### ISSUE TITLE
PyPI publishing is dropped on change to Github Actions

### ISSUE THREAD

**Issue by nothead31** [nidhaloff/deep-translator#81]
The move from Travis to GHA means that the automation no longer builds a package and publishes it to PyPI. I don't have credentials for PyPI yet, and this isn't my work, so you will need to be the one to set up the GHA workflow for publishing. I recommend setting it to publish on new tags, and not every commit.

**Comment by nidhaloff** [comment]
@nothead31 Yes I will add this in GHA asap ;)
