### ISSUE TITLE
ms translation response  - KeyError "translation"

### ISSUE THREAD

**Issue by joej** [nidhaloff/deep-translator#88]
* deep_translator version: 1.5.0 (via pip install)
* Python version: 3.6
* Operating System: Ubuntu 18.04

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

**code**
from deep_translator import single_detection
lang = single_detection( xxx, api_key='yyyyyy')

**results in:** 
   File "./cnki_transform.py", line 478, in <module>
     from deep_translator import single_detection
   File "/home/judge/.local/lib/python3.6/site-packages/deep_translator/__init__.py", line 4, in <module>
     from .google_trans import GoogleTranslator
   File "/home/judge/.local/lib/python3.6/site-packages/deep_translator/google_trans.py", line 5, in <module>
     from .constants import BASE_URLS, GOOGLE_LANGUAGES_TO_CODES
   File "/home/judge/.local/lib/python3.6/site-packages/deep_translator/constants.py", line 194, in <module>
     translation_dict = microsoft_languages_response.json()['translation']
 KeyError: 'translation'

**constants.py**
 microsoft_languages_api_url = "https://api.cognitive.microsofttranslator.com/languages?api-version=3.0&scope=translation"
 microsoft_languages_response = requests.get(microsoft_languages_api_url)
 translation_dict = microsoft_languages_response.json()['translation']

### What I Did
screamed at the keyboard

**steps**
pip install, simple example on language detection, microsoft languages response is borked
A manual grab of the REST endpoint shows a proper JSON response that could have been handled.

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by nothead31** [comment]
Giving this one to @nidhaloff to review & determine if its truly a bug or something else.

**Comment by nidhaloff** [comment]
@joej Hi, so the code is these two lines? is this what caused the error? I'm assuming so because this is the only code that you provided. However, this works fine!

```
from deep_translator import single_detection
lang = single_detection( xxx, api_key='yyyyyy')
```

This piece of code works fine too:

```
microsoft_languages_api_url = "https://api.cognitive.microsofttranslator.com/languages?api-version=3.0&scope=translation"
microsoft_languages_response = requests.get(microsoft_languages_api_url)
translation_dict = microsoft_languages_response.json()['translation']
```

So I'm not sure exactly how can I help. Please provide a reproducible example that I can use to reproduce the error. Somehow you provided a code using the detection API but the error comes from the MS translator, but how did it jump there?
