### ISSUE TITLE
Optimizing Google Translator 

### ISSUE THREAD

**Issue by kuspia** [nidhaloff/deep-translator#93]
### Description

Recently I tried fixing issues #90  #52 with PR #92  which was related to the google translator it was amazing to see the art of web-scraping the translated text using python but the following issues are needed to be solved for a better performance.
**************************************************************************************************************************
1. ```GOOGLE_CODES_TO_LANGUAGES``` dictionary defined in ```constants.py``` is not apt as per the translator link: https://translate.google.com/m

As per the translator database, we have a total of 108 languages with fixed abbreviations that are needed to be cross-checked again with dictionary. Following languages described in the dictionary have the following issues in them.
```
'zh': 'chinese'
'zh-cn': 'chinese (simplified)'
'zh-tw': 'chinese (traditional)'
```
As per the translator database,, we have just one version of the Chinese language whose abbreviation is defined by ```zh-CN```.
```
'tl': 'filipino'
'fil': 'Filipino'
```
As per the translator database, we have just one version of the Filipino language whose abbreviation is defined by ```tl```.
```
'iw': 'hebrew'
'he': 'Hebrew
```
As per the translator database, we have just one version of the Hebrew language whose abbreviation is defined by ```iw```.
```
Kinyarwanda, Odia, Tatar, Uyghur
```
As per the translator database, we have facility to translate them but these languages are not added to dictionary.
**************************************************************************************************************************
2. Why do we get this error for any of the following??  ```There is no support for the chosen language```
```
GoogleTranslator(source='de', target='myanmar').translate('Zwei minimale')
GoogleTranslator(source='de', target='English').translate('Zwei minimale')
GoogleTranslator(source='de', target='kurmanji').translate('Zwei minimale')
```
This is a very serious concern that is needed to be resolved as we are binding the user to enter the language in the specified format of our dictionary, I will explain all of them why it happens so.
The first problem arises because we need to describe the ```myanmar``` as ```myanmar (burmese)``` which forces the user to enter the additional name of language too in brackets.
The second problem arises because we need to describe the ```English``` as ```english``` that forces the user to follow case sensitivity as per the dictionary name.
The third problem arises because we need to describe the ```kurmanji``` as ```kurdish (kurmanji)``` which implies we can't use this translator with other names of any language (if any).
**************************************************************************************************************************

I would like to work on the above, so kindly assign me to fix these issues.

**Comment by nidhaloff** [comment]
@kuspia  alright thanks, I assigned the issue to you

**Comment by kuspia** [comment]
@nidhaloff kindly check out PR #95 that fixes the above issues and also enhances the translator. In case of any confusion kindly ask me.
